appname = casdoor
httpport = 8000
runmode = prod

SessionOn = true
copyrequestbody = true

driverName = mysql
dataSourceName = root:123456@tcp(casdoor-db:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false

redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true

origin = http://casdoor.local:8000