appname = casibase
httpport = 14000
runmode = prod
copyrequestbody = true
disablePreviewMode = true
EnableDocs = true

driverName = mysql
dataSourceName = root:123456@tcp(casibase-db:3306)/
dbName = casibase

casdoorEndpoint = http://casdoor.local:8000
clientId = ba3a96dbc430c5c6a22b
clientSecret = 9228f4ce27971ca5c188cac7489dc0f304a122b6
casdoorOrganization = built-in
casdoorApplication = casibase
redirectPath = /callback
