USE casdoor;

INSERT INTO organization (
  owner,
  name,
  created_time,
  display_name,
  website_url,
  logo,
  logo_dark,
  favicon,
  has_privilege_consent,
  password_type,
  password_salt,
  password_options,
  password_obfuscator_type,
  password_obfuscator_key,
  password_expire_days,
  country_codes,
  default_avatar,
  use_permanent_avatar,
  default_application,
  user_types,
  tags,
  languages,
  master_password,
  default_password,
  master_verification_code,
  ip_whitelist,
  init_score,
  enable_soft_deletion,
  is_profile_public,
  use_email_as_username,
  enable_tour,
  disable_signin,
  ip_restriction,
  nav_items,
  user_nav_items,
  widget_items,
  mfa_items,
  mfa_remember_in_hours,
  account_menu,
  account_items,
  dcr_policy,
  ldap_attributes,
  kerberos_realm,
  kerberos_kdc_host,
  kerberos_keytab,
  kerberos_service_name,
  org_balance,
  user_balance,
  balance_credit,
  balance_currency
) VALUES (
  'admin',
  'ifm',
  DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ'),
  'IFM',
  'https://example.com',
  '',
  '',
  'https://cdn.casbin.org/img/casbin/favicon.ico',
  0,
  'sha512-salt',
  'ifm',
  '["AtLeast6"]',
  '',
  '',
  0,
  '["All"]',
  'https://cdn.casbin.org/img/casbin.svg',
  0,
  '',
  '[]',
  '[]',
  '["en"]',
  '',
  '',
  '',
  '',
  2000,
  0,
  0,
  0,
  1,
  0,
  '',
  'null',
  'null',
  'null',
  'null',
  12,
  '',
  'null',
  'disabled',
  'null',
  '',
  '',
  '',
  '',
  0,
  0,
  0,
  'USD'
) ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  password_type = VALUES(password_type),
  password_salt = VALUES(password_salt),
  password_options = VALUES(password_options),
  country_codes = VALUES(country_codes),
  default_avatar = VALUES(default_avatar),
  languages = VALUES(languages),
  init_score = VALUES(init_score),
  disable_signin = VALUES(disable_signin);

INSERT INTO application (
  owner,
  name,
  created_time,
  display_name,
  category,
  type,
  scopes,
  logo,
  title,
  favicon,
  `order`,
  homepage_url,
  description,
  organization,
  cert,
  default_group,
  header_html,
  page_html,
  enable_password,
  enable_sign_up,
  enable_guest_signin,
  disable_signin,
  enable_signin_session,
  enable_auto_signin,
  enable_code_signin,
  enable_exclusive_signin,
  enable_saml_compress,
  enable_saml_c14n10,
  enable_saml_post_binding,
  disable_saml_attributes,
  enable_saml_assertion_signature,
  use_email_as_saml_name_id,
  enable_web_authn,
  enable_link_with_email,
  org_choice_mode,
  saml_reply_url,
  providers,
  signin_methods,
  signup_items,
  signin_items,
  grant_types,
  tags,
  saml_attributes,
  saml_hash_algorithm,
  saml_c14n_prefix,
  is_shared,
  ip_restriction,
  client_id,
  client_secret,
  client_cert,
  redirect_uris,
  backchannel_logout_uri,
  forced_redirect_origin,
  token_format,
  token_signing_method,
  token_fields,
  token_attributes,
  expire_in_hours,
  refresh_expire_in_hours,
  cookie_expire_in_hours,
  signup_url,
  signin_url,
  forget_url,
  affiliation_url,
  ip_whitelist,
  terms_of_use,
  signup_html,
  signin_html,
  theme_data,
  footer_html,
  form_css,
  form_css_mobile,
  form_offset,
  form_side_html,
  form_background_url,
  form_background_url_mobile,
  failed_signin_limit,
  failed_signin_frozen_time,
  code_resend_timeout,
  custom_scopes,
  domain,
  other_domains,
  upstream_host,
  ssl_mode,
  ssl_cert
) VALUES (
  'admin',
  'casibase',
  DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ'),
  'Casibase',
  'Default',
  'All',
  '[]',
  'https://cdn.casbin.org/img/casdoor-logo_1185x256.png',
  '',
  '',
  0,
  '',
  '',
  'built-in',
  'cert-built-in',
  '',
  '',
  '',
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '',
  '',
  '[{"owner":"","name":"provider_captcha_default","canSignUp":false,"canSignIn":false,"canUnlink":false,"bindingRule":null,"countryCodes":null,"prompted":false,"signupGroup":"","rule":"","provider":null},{"owner":"admin","name":"provider-storage-ifm-minio-v1","canSignUp":false,"canSignIn":false,"canUnlink":false,"bindingRule":null,"countryCodes":null,"prompted":false,"signupGroup":"","rule":"","provider":null}]',
  '[{"name":"Password","displayName":"Password","rule":"All"},{"name":"Verification code","displayName":"Verification code","rule":"All"}]',
  '[{"name":"ID","visible":false,"required":true,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"Random"},{"name":"Username","visible":true,"required":true,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"None"},{"name":"Display name","visible":true,"required":true,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"None"},{"name":"Password","visible":true,"required":true,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"None"},{"name":"Confirm password","visible":true,"required":true,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"None"},{"name":"Email","visible":true,"required":false,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"Normal"},{"name":"Signup button","visible":true,"required":true,"prompted":false,"type":"","customCss":"","label":"","placeholder":"","options":null,"regex":"","rule":"None"}]',
  '[{"name":"Logo","visible":true,"label":"","customCss":"","placeholder":"","rule":"None","isCustom":false},{"name":"Signin methods","visible":true,"label":"","customCss":"","placeholder":"","rule":"None","isCustom":false},{"name":"Username","visible":true,"label":"","customCss":"","placeholder":"","rule":"None","isCustom":false},{"name":"Password","visible":true,"label":"","customCss":"","placeholder":"","rule":"None","isCustom":false},{"name":"Login button","visible":true,"label":"","customCss":"","placeholder":"","rule":"None","isCustom":false},{"name":"Signup link","visible":true,"label":"","customCss":"","placeholder":"","rule":"None","isCustom":false}]',
  '["authorization_code","password","client_credentials","token","id_token","refresh_token"]',
  '[]',
  'null',
  '',
  '',
  1,
  '',
  'ba3a96dbc430c5c6a22b',
  '9228f4ce27971ca5c188cac7489dc0f304a122b6',
  '',
  '["http://casibase.local:14000/callback","http://localhost:14000/callback"]',
  '',
  '',
  'JWT',
  '',
  '[]',
  'null',
  168,
  168,
  720,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  NULL,
  '',
  '',
  '',
  2,
  '',
  '',
  '',
  5,
  15,
  0,
  '[]',
  '',
  'null',
  '',
  '',
  ''
) ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  organization = VALUES(organization),
  cert = VALUES(cert),
  enable_password = VALUES(enable_password),
  enable_sign_up = VALUES(enable_sign_up),
  is_shared = VALUES(is_shared),
  client_id = VALUES(client_id),
  client_secret = VALUES(client_secret),
  redirect_uris = VALUES(redirect_uris),
  providers = VALUES(providers),
  signin_methods = VALUES(signin_methods),
  signup_items = VALUES(signup_items),
  signin_items = VALUES(signin_items),
  grant_types = VALUES(grant_types),
  token_format = VALUES(token_format);

INSERT INTO `user` (
  owner,
  name,
  created_time,
  updated_time,
  deleted_time,
  id,
  external_id,
  type,
  password,
  password_salt,
  password_type,
  display_name,
  first_name,
  last_name,
  avatar,
  avatar_type,
  permanent_avatar,
  email,
  email_verified,
  phone,
  country_code,
  region,
  location,
  address,
  affiliation,
  title,
  id_card_type,
  id_card,
  real_name,
  is_verified,
  homepage,
  bio,
  tag,
  language,
  gender,
  birthday,
  education,
  score,
  karma,
  ranking,
  balance,
  balance_credit,
  currency,
  balance_currency,
  is_default_avatar,
  is_online,
  is_admin,
  is_forbidden,
  is_deleted,
  signup_application,
  hash,
  pre_hash,
  register_type,
  register_source,
  created_ip,
  last_signin_time,
  last_signin_ip,
  invitation,
  invitation_code,
  cart,
  ldap,
  properties,
  roles,
  permissions,
  `groups`,
  last_change_password_time,
  last_signin_wrong_time,
  signin_wrong_times,
  mfa_items,
  mfa_remember_deadline,
  need_update_password,
  ip_whitelist,
  application_scopes
) VALUES (
  'ifm',
  'user',
  DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ'),
  '',
  '',
  UUID(),
  '',
  'normal-user',
  SHA2(CONCAT(SHA2('user', 512), 'ifm'), 512),
  'ifm',
  'sha512-salt',
  'Default User',
  'Default',
  'User',
  'https://cdn.casbin.org/img/casbin.svg',
  '',
  '',
  'user@example.com',
  0,
  '',
  '',
  '',
  '',
  '[]',
  '',
  '',
  '',
  '',
  '',
  0,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  2000,
  0,
  1,
  0,
  0,
  '',
  'USD',
  1,
  0,
  0,
  0,
  0,
  'casibase',
  '',
  '',
  'Add User',
  'seed-casdoor',
  '',
  '',
  '',
  '',
  '',
  'null',
  '',
  'null',
  '[]',
  '[]',
  '[]',
  '',
  '',
  0,
  'null',
  '',
  0,
  '',
  '[]'
) ON DUPLICATE KEY UPDATE
  password = VALUES(password),
  password_salt = VALUES(password_salt),
  password_type = VALUES(password_type),
  display_name = VALUES(display_name),
  first_name = VALUES(first_name),
  last_name = VALUES(last_name),
  email = VALUES(email),
  avatar = VALUES(avatar),
  type = VALUES(type),
  is_admin = VALUES(is_admin),
  is_forbidden = VALUES(is_forbidden),
  is_deleted = VALUES(is_deleted),
  need_update_password = VALUES(need_update_password),
  signup_application = VALUES(signup_application),
  register_source = VALUES(register_source);

INSERT INTO provider (
  owner,
  name,
  created_time,
  display_name,
  category,
  type,
  sub_type,
  method,
  client_id,
  client_secret,
  endpoint,
  intranet_endpoint,
  domain,
  bucket,
  path_prefix,
  provider_url,
  enable_proxy,
  state
) VALUES (
  'admin',
  'provider-storage-ifm-minio-v1',
  DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ'),
  'IFM MinIO Storage v1',
  'Storage',
  'MinIO',
  '',
  '',
  'minioadmin',
  'minioadmin',
  'http://minio:9000',
  'http://minio:9000',
  'http://minio:9000',
  'casibase',
  'ifm-v0',
  '',
  0,
  'Active'
) ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  category = VALUES(category),
  type = VALUES(type),
  client_id = VALUES(client_id),
  client_secret = VALUES(client_secret),
  endpoint = VALUES(endpoint),
  intranet_endpoint = VALUES(intranet_endpoint),
  domain = VALUES(domain),
  bucket = VALUES(bucket),
  path_prefix = VALUES(path_prefix),
  state = VALUES(state);
