USE casibase;

INSERT INTO store (
  owner,
  name,
  created_time,
  display_name,
  storage_provider,
  storage_subpath,
  image_provider,
  split_provider,
  search_provider,
  model_provider,
  embedding_provider,
  text_to_speech_provider,
  enable_tts_streaming,
  speech_to_text_provider,
  agent_provider,
  tool_providers,
  vector_store_id,
  builtin_tools,
  memory_limit,
  frequency,
  limit_minutes,
  knowledge_count,
  suggestion_count,
  welcome,
  welcome_title,
  welcome_text,
  prompt,
  example_questions,
  theme_color,
  avatar,
  title,
  html_title,
  favicon_url,
  logo_url,
  footer_html,
  nav_items,
  vector_stores,
  child_stores,
  child_model_providers,
  forbidden_words,
  owners,
  show_auto_read,
  disable_file_upload,
  hide_thinking,
  enable_extra_options,
  is_default,
  state,
  shared_by,
  file_tree,
  properties_map
)
SELECT
  owner,
  'ifm-v0',
  DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ'),
  'IFM v0',
  'provider-storage-ifm-minio-v1',
  'ifm-v0',
  image_provider,
  split_provider,
  search_provider,
  model_provider,
  embedding_provider,
  text_to_speech_provider,
  enable_tts_streaming,
  speech_to_text_provider,
  agent_provider,
  tool_providers,
  vector_store_id,
  builtin_tools,
  memory_limit,
  frequency,
  limit_minutes,
  knowledge_count,
  suggestion_count,
  welcome,
  welcome_title,
  welcome_text,
  prompt,
  example_questions,
  theme_color,
  avatar,
  title,
  html_title,
  favicon_url,
  logo_url,
  footer_html,
  nav_items,
  vector_stores,
  child_stores,
  child_model_providers,
  forbidden_words,
  owners,
  show_auto_read,
  disable_file_upload,
  hide_thinking,
  enable_extra_options,
  0,
  'Active',
  shared_by,
  file_tree,
  properties_map
FROM store
WHERE owner = 'admin' AND name = 'store-built-in'
ON DUPLICATE KEY UPDATE
  state = VALUES(state);

UPDATE store
SET
  storage_provider = 'provider-storage-ifm-minio-v1',
  storage_subpath = 'ifm-v0'
WHERE owner = 'admin' AND name = 'ifm-v0';

INSERT INTO store (
  owner,
  name,
  created_time,
  display_name,
  storage_provider,
  storage_subpath,
  image_provider,
  split_provider,
  search_provider,
  model_provider,
  embedding_provider,
  text_to_speech_provider,
  enable_tts_streaming,
  speech_to_text_provider,
  agent_provider,
  tool_providers,
  vector_store_id,
  builtin_tools,
  memory_limit,
  frequency,
  limit_minutes,
  knowledge_count,
  suggestion_count,
  welcome,
  welcome_title,
  welcome_text,
  prompt,
  example_questions,
  theme_color,
  avatar,
  title,
  html_title,
  favicon_url,
  logo_url,
  footer_html,
  nav_items,
  vector_stores,
  child_stores,
  child_model_providers,
  forbidden_words,
  owners,
  show_auto_read,
  disable_file_upload,
  hide_thinking,
  enable_extra_options,
  is_default,
  state,
  shared_by,
  file_tree,
  properties_map
)
SELECT
  owner,
  'ifm-minio-v0',
  DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ'),
  'IFM MinIO v0',
  'provider-storage-ifm-minio-v1',
  'ifm-minio-v0',
  image_provider,
  split_provider,
  search_provider,
  model_provider,
  embedding_provider,
  text_to_speech_provider,
  enable_tts_streaming,
  speech_to_text_provider,
  agent_provider,
  tool_providers,
  vector_store_id,
  builtin_tools,
  memory_limit,
  frequency,
  limit_minutes,
  knowledge_count,
  suggestion_count,
  welcome,
  welcome_title,
  welcome_text,
  prompt,
  example_questions,
  theme_color,
  avatar,
  title,
  html_title,
  favicon_url,
  logo_url,
  footer_html,
  nav_items,
  vector_stores,
  child_stores,
  child_model_providers,
  forbidden_words,
  owners,
  show_auto_read,
  disable_file_upload,
  hide_thinking,
  enable_extra_options,
  0,
  'Active',
  shared_by,
  file_tree,
  properties_map
FROM store
WHERE owner = 'admin' AND name = 'ifm-v0'
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  storage_provider = VALUES(storage_provider),
  storage_subpath = VALUES(storage_subpath),
  image_provider = VALUES(image_provider),
  split_provider = VALUES(split_provider),
  search_provider = VALUES(search_provider),
  model_provider = VALUES(model_provider),
  embedding_provider = VALUES(embedding_provider),
  state = VALUES(state);
